// vue-headless/src/exemple/HorizontalList/HorizontalUserList.vue
<template>
  <div style="display: flex; flex-direction: row; column-gap: 5px">
    <div
        v-for="user in users"
        :key="user.id"
    >
      <div style=" width: 200px; border: 2px solid blue; border-radius: 5px; padding: 0 0.5em">
        {{ user.firstname }} {{ user.lastname }}
      </div>
    </div>
  </div>
</template>


<script setup lang="ts">
import {useWatch} from "../List/useWatch.ts";
import {CustomList} from "../List/CustomList.ts";
import {User} from "../../mock/users.ts";

const {listStore} = defineProps({
  listStore: CustomList<User>,
})
const {filteredItems: users} = useWatch(listStore!)
</script>

// react-headless/src/components/exemple-5/HorizontalUserList/HorizontalUserList.tsx
import { Card, Row } from "antd";
import { CustomList } from "../List/CustomList";
import { useWatch } from "../List/useWatch";
import { User } from "../../../mock/users";

interface HorizontalListProps {
  listStore: CustomList<User>;
}

export function HorizontalUserList({ listStore }: HorizontalListProps) {
  const { filteredItems: users } = useWatch(listStore);
  return (
    <Row
      style={{
        width: "500px",
        overflowX: "auto",
        flexDirection: "row",
        columnGap: "1em",
      }}
      wrap={false}
    >
      {users.map(({ firstname, lastname, id }) => {
        return (
          <Card style={{ width: "150px" }} key={id}>
            {firstname} {lastname}
          </Card>
        );
      })}
    </Row>
  );
}
