// solid-headless/src/exemple/List/useWatch.ts
import {CustomList} from "./CustomList";
import {createStore} from "solid-js/store";
import {createEffect, onCleanup} from "solid-js";

export function useWatch<ItemType>(listStore: CustomList<ItemType>) {
    const [filteredItems, setFilteredItems] = createStore(listStore.getFilteredItems())

    createEffect(() => {
        const listenerId = listStore.subscribe(()=>{
            setFilteredItems(listStore.getFilteredItems())
        })
        onCleanup(()=> listStore.unsubscribe(listenerId) )
    })

    return {filteredItems};
}

// react-headless/src/components/exemple-5/List/useWatch.ts
import { useEffect, useState } from "react";
import { CustomList } from "./CustomList";

export function useWatch<ItemType>(listStore: CustomList<ItemType>) {
  const [, forceUpdate] = useState({});

  useEffect(() => {
    const listenerId = listStore.subscribe(() => forceUpdate({}));
    return () => listStore.unsubscribe(listenerId);
  });

  return { filteredItems: listStore.getFilteredItems() };
}
